# Example configuration file for the Discord bot
# Copy this file to config.toml and modify the values as needed

# Logging configuration
[log]
level = 'info'      # Log level: debug, info, warn, error
format = 'text'     # Output format: text or json
add_source = true   # Include source file and line in log output
no_color = false    # Disable colored output

# Discord bot configuration
[bot]
dev_mode = false         # Enable development mode
sync_commands = true     # Sync slash commands on startup
guild_ids = []          # List of guild IDs to register commands in (empty for global)
token = ""              # Discord bot token (required)
gateway_url = ""        # Custom gateway URL (optional)
rest_url = ""          # Custom REST API URL (optional)

# External API configuration
[external]
raiderio_key = ""      # Raider.IO API key (required for WoW features)

# Database configuration
[database]
driver = 'sqlite'       # Database driver: 'sqlite' or 'postgres'
database = 'mukabi.db'  # SQLite file path or PostgreSQL database name

# PostgreSQL-specific settings (uncomment if using PostgreSQL)
# host = 'localhost'    # Database host
# port = 5432          # Database port
# username = ''        # Database username
# password = ''        # Database password
# ssl_mode = 'disable' # SSL mode: disable, require, verify-ca, verify-full
